### ISSUE TITLE
Look into var for Vendor folder

### ISSUE THREAD

**Issue by patricklittle** [BarkleyUS/blastoff#2]
Can we have a variable that would link to our vendor and bower_components folder?

**Comment by smacpherson64** [comment]
This should be added to barkley-blastoff 0.1.15:

We are using: https://github.com/sass/node-sass#includepaths which gulp sass pipes directly to node sass.

> includePaths
> Type: Array<String> Default: []
> An array of paths that libsass can look in to attempt to resolve your @import declarations. When using data, it is recommended that you use this.
